# Generated by Django 5.0.3 on 2024-12-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
